version: '3.8'
name: 'index-infra'
services:
  jenkins-docker:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    environment:
      DOCKER_TLS_CERTDIR: /certs
    volumes:
      - jenkins-docker-certs:/certs/client
      - jenkins-data:/var/jenkins_home
    networks:
      jenkins:
        aliases:
          - docker
    ports:
      - "2376:2376"

  jenkins-blueocean:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-blueocean
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: "1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-data:/var/jenkins_home
    networks:
      jenkins:
        aliases:
          - blueocean
    ports:
      - "21823:8080"
      - "50000:50000"

networks:
  jenkins:

volumes:
  jenkins-docker-certs:
  jenkins-data:
